name: 执行筛选脚本

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安装Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install json5 requests
    - name: 执行筛选脚本
      run: python main.py
    - name: 推送
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com 
        git add .
        git commit -m "update new.json"
        git push
