name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install json5 requests
    - name: Run Python script
      run: python dataSift.py
    - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: new.json
          path: ${{ github.workspace }}/new.json
